apiVersion: v2
name: gameledger
description: App to keep track of card and board game wins losses
type: application
version: "0.1.0"
appVersion: "0.1.0"
home: https://github.com/janip81/helm-charts/tree/main/charts/gameledger
# icon: https://www.home-assistant.io/images/favicon-192x192.png
maintainers:
  - name: janip81
    email: jani@techmonkeys.se
    url: https://github.com/janip81
keywords:
  - gameledger
sources:
  - https://github.com/janip81/helm-charts/tree/main/charts/gameledger/
deprecated: false
annotations:
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/janip81/helm-charts/tree/main/charts/gameledger/
