apiVersion: v2
name: capi-cluster
description: An unofficial Helm chart to deploy workload cluster with Cluster API

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.25

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.0.5
home: https://github.com/janip81/helm-charts/tree/main/charts/capi-cluster
icon: https://raw.githubusercontent.com/janip81/helm-charts/.logos/capi-logo.svg
keywords:
  - cluster-api
maintainers:
  - name: Jani Pesonen
    email: jani@techmonkeys.se
    url: https://github.com/janip81
sources:
  - https://github.com/janip81/helm-charts/tree/main/charts/capi-cluster
  - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere
  - https://github.com/kubernetes-sigs/cluster-api