{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "matrix-synapse.fullname" . }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentGatewayName }}
      namespace: {{ .Values.gateway.parentGatewayNamespace }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "matrix-synapse.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
