apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-secrets
type: Opaque
data:
  registration_shared_secret: {{ ( .Values.secrets.registrationSharedSecret | default (randAlphaNum 64) ) | b64enc }}
  macaroon_secret_key: {{ ( .Values.secrets.macaroonSecretKey | default (randAlphaNum 64) ) | b64enc }}
  form_secret: {{ ( .Values.secrets.formSecret | default (randAlphaNum 64) ) | b64enc }}
