---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
  name: {{ .Values.cluster.name }}-crs-0
  namespace: {{ .Values.cluster.name }}
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
  resources: {{ include "ClusterResourceSet.AddonsFalse" .Values.addons }}
{{ if (default .Values.addons.install_vsphere_addon false)}}
  - kind: Secret
    name: vsphere-csi-controller
  - kind: ConfigMap
    name: vsphere-csi-controller-role
  - kind: ConfigMap
    name: vsphere-csi-controller-binding
  - kind: Secret
    name: csi-vsphere-config
  - kind: ConfigMap
    name: csi.vsphere.vmware.com
  - kind: ConfigMap
    name: vsphere-csi-node
  - kind: ConfigMap
    name: vsphere-csi-controller
  - kind: Secret
    name: cloud-controller-manager
  - kind: Secret
    name: cloud-provider-vsphere-credentials
  - kind: ConfigMap
    name: cpi-manifests
{{ end }}
